"""Add Conversation model

Revision ID: 988b9f2aed05
Revises: 287cc31f6971
Create Date: 2024-12-23 14:16:13.034902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988b9f2aed05'
down_revision: Union[str, None] = '287cc31f6971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('inferred_command', sa.Text(), nullable=True),
    sa.Column('ideal_inference', sa.Text(), nullable=True),
    sa.Column('initial_review_by', sa.Integer(), nullable=True),
    sa.Column('final_review_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['final_review_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initial_review_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
