"""minor change

Revision ID: fd1883cbbbcd
Revises: 504ee90c1d9d
Create Date: 2024-12-31 16:28:57.721613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1883cbbbcd'
down_revision: Union[str, None] = '504ee90c1d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_conversation_id_key', 'conversations', type_='unique')
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.drop_constraint('conversations_final_review_by_fkey', 'conversations', type_='foreignkey')
    op.drop_constraint('conversations_initial_review_by_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['initial_review_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversations', 'users', ['final_review_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key('conversations_initial_review_by_fkey', 'conversations', 'users', ['initial_review_by'], ['id'])
    op.create_foreign_key('conversations_final_review_by_fkey', 'conversations', 'users', ['final_review_by'], ['id'])
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.create_unique_constraint('conversations_conversation_id_key', 'conversations', ['conversation_id'])
    # ### end Alembic commands ###
