services:
  web:
    container_name: voiceagent_web_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 5 --limit-max-requests 1000 --log-level info --forwarded-allow-ips='*' --proxy-headers"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  redis:
    container_name: redis_prod
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data/
    expose:
      - 6379

  celery:
    container_name: celery_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A app.celery.celery worker -l info
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - web

  flower:
    container_name: flower_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A app.celery.celery flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    env_file:
      - ./.env.prod
    depends_on:
      - celery

  nginx-proxy:
    container_name: nginx-proxy_prod
    build: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  acme-companion:
    container_name: acme-companion_prod
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  redis_data:
  certs:
  html:
  vhost:
  acme: